spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://10.103.223.223:8083
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service

        - id: contract
          uri: http://10.102.132.247:8084
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service

        - id: complains
          uri: http://10.105.149.2:8085
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

server:
  port: 8080
