spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${POSTS_ROUTE_URI:http://authregister-svc:8083}
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service

        - id: contract
          uri: ${COMMENTS_ROUTE_URI:http://addcontracy-showlist-svc:8084}
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service
        - id: complains
          uri: ${COMMENTSs_ROUTE_URI:http://complains-svc:8085}
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

server:
  port: 8080